---
title: "Untitled"
author: "Jessalyn Lim"
date: "2023-08-05"
output: html_document
---

```{r install-packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
library(naniar)
library(readxl)
library(rvest)
library(measurements)
library(polite)
library(janitor)
library(tools)
library(openxlsx)
library("berryFunctions")
```


```{r}
tour_link <- bow("https://en.wikipedia.org/wiki/%2B%E2%80%93%3D%C3%B7%C3%97_Tour") %>% scrape()

tour_data_2022 <- tour_link %>% 
  html_nodes(xpath = '//*[@id="mw-content-text"]/div[1]/table[2]') %>% 
  html_table() %>% 
  as.data.frame()

colnames(tour_data_2022)[1] <- "Date"

tour_data_2023 <- tour_link %>% 
  html_nodes(xpath = '//*[@id="mw-content-text"]/div[1]/table[3]') %>% 
  html_table() %>% 
  as.data.frame()

colnames(tour_data_2023)[1] <- "Date"

tour_data <- tour_data_2022 %>% 
  bind_rows(tour_data_2023) %>% 
  separate(Attendance, c("Attendance", "Capacity"), " / ")

write.csv(tour_data, "tour_data.csv", row.names = FALSE)
```



```{r}
setlist_data <- tour_link %>% 
  html_nodes(xpath = '//*[@id="mw-content-text"]/div[1]/div[2]/ol') %>% 
  html_text()

setlist_data <- strsplit(setlist_data, split = '"\n\"') %>% 
  as.data.frame(col.names = c("song_name"))
encore <- setlist_data[20, "song_name"] %>% 
  strsplit(split = "\n") %>% 
  as.data.frame()

encore <- encore[-c(2),]
encore <- gsub('[\"]', '', encore) %>% as.vector()

setlist_data <- insertRows(setlist_data, 20, new = c(encore[1]))
setlist_data <- insertRows(setlist_data, 21, new = c(encore[2]))
setlist_data <- setlist_data[-c(22),] %>% as.data.frame()

setlist_data$. <- gsub('"','',as.character(setlist_data$.))

colnames(setlist_data) <- c("song_name")

write.csv(setlist_data, "setlist_data.csv", row.names = FALSE)
```



```{r}
test <- tour_link %>% 
  html_nodes(xpath = '//*[@id="mw-content-text"]/div[1]/div[2]/ol') %>% 
  

test2 <- strsplit(test, split = '"\n\"') %>% 
  as.data.frame(col.names = c("song_name"))
test3 <- test2[20, "song_name"] %>% 
  strsplit(split = "\n") %>% 
  as.data.frame()

test3 <- test3[-c(2),]
test4 <- gsub('[\"]', '', test3) %>% as.vector()

test5 <- rbind(test2[1:19,],
      c(test4[1]),
      c(test4[2]),
      test2[21:22,])

test6 <- insertRows(test2, 20, new = c(test4[1]))
test6 <- insertRows(test6, 21, new = c(test4[2]))
test6 <- test6[-c(22),] %>% as.data.frame()

test6$. <- gsub('"','',as.character(test6$.))

colnames(test6) <- c("song_name")

write.csv(fifa_wwc_3x3_2023_games, "fifa_wwc_3x3_2023_games.csv", row.names = FALSE)
```



``` {r basketball-reference}
fifa_wwc_3x3_2023_wikipedia_link <- bow("https://en.wikipedia.org/wiki/2023_FIBA_3x3_World_Cup_%E2%80%93_Women%27s_tournament") %>% scrape()
fifa_wwc_3x3_2023_wikipedia <- fifa_wwc_3x3_2023_wikipedia_link %>% 
  html_nodes(xpath = '//*[@id="mw-content-text"]/div[1]/table[2]') %>% 
  html_table() %>% 
  as.data.frame() %>% 
  select(Competition, Qualified)



fifa_wwc_3x3_2023_wikipedia$Competition <- gsub("\\[.*\\]","", fifa_wwc_3x3_2023_wikipedia$Competition)

head(fifa_wwc_3x3_2023_wikipedia)

delim_space1 <- str_sub(fifa_wwc_3x3_2023_wikipedia$Qualified[2],6,6)
fifa_wwc_3x3_2023_wikipedia <- fifa_wwc_3x3_2023_wikipedia %>% 
  separate_longer_delim(Qualified, delim_space1)

write.csv(fifa_wwc_3x3_2023_wikipedia, "fifa_wwc_3x3_2023_wikipedia.csv", row.names = FALSE)
```



```{r}
teams_url <- "https://fiba3x3.com/2023/worldcup/stats/women/teams"
teams_html <- read_html(teams_url)

fifa_wwc_3x3_2023_teams <- teams_html %>% 
  html_nodes(".DataTable") %>% 
  html_table() %>% 
  as.data.frame()

delim_space2 <- str_sub(fifa_wwc_3x3_2023_teams$Team[1],3,3)

fifa_wwc_3x3_2023_teams$Team <- gsub(paste0(".*\\.", delim_space2),"",fifa_wwc_3x3_2023_teams$Team)


write.csv(fifa_wwc_3x3_2023_teams, "fifa_wwc_3x3_2023_teams.csv", row.names = FALSE)

```






```{r}
players_url <- "https://fiba3x3.com/2023/worldcup/stats/women/players"
players_html <- read_html(players_url)

fifa_wwc_3x3_2023_players <- players_html %>% 
  html_nodes(".DataTable") %>% 
  html_table() %>% 
  as.data.frame()

delim_space2 <- str_sub(fifa_wwc_3x3_2023_players$Player[1],3,3)

fifa_wwc_3x3_2023_players$Player <- gsub(paste0(".*\\.", delim_space2),"",fifa_wwc_3x3_2023_players$Player)


write.csv(fifa_wwc_3x3_2023_players, "fifa_wwc_3x3_2023_players.csv", row.names = FALSE)
```


```{r}
games_url <- "https://fiba3x3.com/2023/worldcup/stats/women/fastest-games"
games_html <- read_html(games_url)

fifa_wwc_3x3_2023_games <- games_html %>% 
  html_nodes(".DataTable") %>% 
  html_table() %>% 
  as.data.frame() %>% 
  select(Game, Round, Score, Playing.time)


write.csv(fifa_wwc_3x3_2023_games, "fifa_wwc_3x3_2023_games.csv", row.names = FALSE)

```

```{r}
fifa_wwc_3x3_2023_wikipedia
fifa_wwc_3x3_2023_teams
fifa_wwc_3x3_2023_players
fifa_wwc_3x3_2023_games
```

```{r}
aussie_players <- fifa_wwc_3x3_2023_players %>% 
  filter(Team == 'Australia') %>% 
  mutate(`1PTAPG` = X1PTA / GP,
         `1PTMPG` = X1PTM / GP,
         `2PTAPG` = X2PTA / GP,
         `2PTMPG` = X2PTM / GP,
         `FTAPG` = FTA / GP,
         `FTMPG` = FTM / GP) %>% 
  gather(variable, value, -c(Player, Team))

write.csv(aussie_players, "aussie_players.csv", row.names = FALSE)

```




```{r}
all_players <- fifa_wwc_3x3_2023_players %>% 
  mutate(BSPG = BS / GP,
         DRVPG = DRV / GP,
         KASPG = KAS / GP) %>% 
  select(Player, Team, PPG, HGLPG, REBPG, TOPG, BSPG, DRVPG, KASPG) %>% 
  gather(variable, value, -c(Player, Team))

write.csv(all_players, "all_players.csv", row.names = FALSE)
```

```{r}

```

